# Generated by Django 2.0.1 on 2018-03-14 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180124_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
