# Generated by Django 2.0.1 on 2018-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180328_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='username',
            field=models.CharField(default='anonymous', max_length=140),
            preserve_default=False,
        ),
    ]
