# Generated by Django 2.0.1 on 2018-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('link', models.URLField(max_length=450)),
                ('picture', models.URLField(max_length=450)),
            ],
        ),
    ]
