# Generated by Django 2.0.1 on 2018-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='picture',
            field=models.URLField(blank=True, max_length=450, null=True),
        ),
    ]
